- hosts: all
  tasks:
    - name: Make Sure Buffalo Drive Docs Backup Completed, Pat
      shell: grep "received" "/Users/thenormans/Buffalo/Pat/Pats_Documents/Sync/`date '+%Y%m%d'`.log"
      register: out_pat
      ignore_errors: yes
      failed_when: out_pat.rc >= 1

    - debug:
        msg: out_pat.stdout

    - name: Make Sure Buffalo Drive Docs Backup Completed, Julie
      shell: grep "received" "/Users/thenormans/Buffalo/Julie/Julie_Documents/Sync/`date '+%Y%m%d'`.log"
      register: out_julie
      ignore_errors: yes
      failed_when: out_julie.rc >= 1

    - debug:
        msg: out_julie.stdout

