- name: File Testing
  hosts: all
  tasks:
  - name: ensure file exists
    copy:
      content: ""
      dest: /tmp/ansibleTest.txt
      force: no
      group: sys
      owner: root
      mode: 0555
