- hosts: all
  tasks:
    - name: Get TimeMachine Last Result
      shell: /usr/bin/syslog -F '$Time $Message' -k Sender com.apple.backupd -k Time ge -59m | tail -n 3
      register: out

    - debug: var=out.stdout_lines

    - set_fact:
      string_to_echo: "{{ out.stdout_lines }}"
